services:
    samba:
        image: vollborn/samba
        build:
            context: ./src
            dockerfile: Dockerfile
        ports:
            - "139:139"
            - "445:445"
        volumes:
            - "./users.env:/samba/users.env"
            - "./smb.conf:/samba/smb.conf"
            - "./data:/samba/data"
